### PR TITLE
Fixed some compiler warnings in eTrice C runtime.

### PR DESCRIPTION
**Pull request by florianbehrens**

### CODE REVIEW

**Comment by hrentzreichert** [comment]
Thanks for the contribution which we appreciate.
We will review the changes and get back to you.

In case we would like to integrate your changes you need to sign a CLA at eclipse.org: http://www.eclipse.org/legal/CLA.php

**Comment by hrentzreichert** [comment]
See also the CONTRIBUTING.txt contained in the top level of our Git repository.

**Comment by hrentzreichert** [comment]
... and https://wiki.eclipse.org/Development_Resources/Contributing_via_Git

**Comment by jungthom** [comment]
Thanks for the contribution.

**Pull request merged**
